INCLUDES=-I stdlib -I utils -I parsing

GENLIB=stdlib/pervasives.cmi \
  stdlib/array.cmi stdlib/list.cmi stdlib/char.cmi stdlib/string.cmi stdlib/sys.cmi \
  stdlib/hashtbl.cmi stdlib/sort.cmi stdlib/marshal.cmi \
  stdlib/int32.cmi stdlib/int64.cmi stdlib/nativeint.cmi \
  stdlib/obj.cmi stdlib/lexing.cmi stdlib/parsing.cmi \
  stdlib/set.cmi stdlib/map.cmi \
  stdlib/stack.cmi stdlib/queue.cmi \
  stdlib/stream.cmi \
  stdlib/buffer.cmi stdlib/printf.cmi stdlib/format.cmi \
  stdlib/arg.cmi stdlib/printexc.cmi stdlib/gc.cmi \
  stdlib/digest.cmi stdlib/random_state.cmi stdlib/random.cmi stdlib/callback.cmi \
  stdlib/genlex.cmi stdlib/weak.cmi \
  stdlib/filename.cmi stdlib/complex.cmi stdlib/scanning.cmi stdlib/scanf.cmi

PUBLIC=parsing/location.cmi parsing/parsetree.cmi parsing/parse.cmi

all: clean $(GENLIB) $(PUBLIC)
	ocamldoc.opt -html $(INCLUDES) -d doc/libref $(GENLIB:.cmi=.mli) $(PUBLIC:.cmi=.mli)
.PHONY: all

stdlib/pervasives.cmi: stdlib/pervasives.mli
	ocamlc.opt -nopervasives -nostdlib $(INCLUDES) -c $<

%.cmi: %.mli
	ocamlc.opt -nostdlib $(INCLUDES) -c $<

genlib_intfs:
	cd stdlib; make -f Makefile.doc
.PHONY: genlib_intfs

clean:
	rm -f */*.cmi
.PHONY: clean

include .depend
