#!/bin/sh
#########################################################################
#                                                                       #
#                            Objective Caml                             #
#                                                                       #
#            Xavier Leroy, projet Cristal, INRIA Rocquencourt           #
#                                                                       #
#   Copyright 2004 Institut National de Recherche en Informatique et    #
#   en Automatique.  All rights reserved.  This file is distributed     #
#   under the terms of the GNU Library General Public License, with     #
#   the special exception on linking described in file ../LICENSE.      #
#                                                                       #
#########################################################################

# $Id: Compflags 10443 2010-05-20 09:44:25Z doligez $

case $1 in
  pervasives.cm[iox]|pervasives.p.cmx) echo ' -nopervasives';;
  scanf.cmx|scanf.p.cmx) echo ' -inline 9';;
  *) echo ' ';;
esac
