TOPDIR=$(BASEDIR)/..
LLAMARUN=$(TOPDIR)/back/byterun/llamarun
LLAMAC=$(LLAMARUN) $(TOPDIR)/back/bytec/llamac

.SUFFIXES: .ml .lml .lmo # .mli .lmi 

.mli.lmi:
	$(LLAMAC) -c -g $(INCLUDES) $<
.ml.lmo:
	$(LLAMAC) -c -g $(INCLUDES) $<

defaultclean:
	rm -f *.lmi *.lmo
.PHONY: defaultclean
