all::
	@-echo "-- Making all in" basics; cd basics; make all

clean::
	@-echo "-- Making clean in" basics; cd basics; make clean

all::
	@-echo "-- Making all in" calc; cd calc; make all

clean::
	@-echo "-- Making clean in" calc; cd calc; make clean

all::
	@-echo "-- Making all in" compress; cd compress; make all

clean::
	@-echo "-- Making clean in" compress; cd compress; make clean

all::
	@-echo "-- Making all in" docteur; cd docteur; make all

clean::
	@-echo "-- Making clean in" docteur; cd docteur; make clean

all::
	@-echo "-- Making all in" hanoi; cd hanoi; make all

clean::
	@-echo "-- Making clean in" hanoi; cd hanoi; make clean

all::
	@-echo "-- Making all in" kb; cd kb; make all

clean::
	@-echo "-- Making clean in" kb; cd kb; make clean
