BOOTDIR=../boot
LIBRARY=backlib
INCLUDES=-I ../stdlib
MODULES=consistbl location fatal tbl ident asttypes primitive lambda printlambda

include ../Make/generic.mk
include ../Make/lib.mk
include ../Make/ocamllib.mk
