BOOTDIR=../../boot
BINARY=llamac
INCLUDES=-I ../../stdlib -I ../../backlib -I ../../frontlib -I ../bytelib
RUNTIME_PATH=../byterun
LIBRARIES=backlib frontlib bytelib
MODULES=main

include ../../config.mk
include ../../Make/generic.mk
include ../../Make/app.mk
include ../../Make/ocamlapp.mk
