BOOTDIR=../../boot
BINARY=llamac
INCLUDES=-I ../../stdlib -I ../../backlib -I ../../frontlib -I ../bytelib
RUNTIME_PATH=-../../back/byterun
LIBRARIES=stdlib backlib frontlib bytelib
MODULES=main

include ../../config.mk
include ../../Make/generic.mk
include ../../Make/app.mk
include ../../Make/ocamlapp.mk
